### ISSUE TITLE
Wrong status code (200) when try get non existig id object

### ISSUE THREAD

**Issue by hubert-wojtowicz** [fchristl/express-json-file-crud#1]
Hi, please allow me to push branch and create a pull request to your repo, as I found bug described in issue title.

**Comment by fchristl** [comment]
Hey @hubert-wojtowicz, thanks for your interest in submitting a pull request :-)! You should be able to clone the repository, fix the issue and then submit a pull request to this repository. Does that work for you?

**Comment by hubert-wojtowicz** [comment]
@fchristl, I like your solution as it very fast allows to set up simple REST API.

Pushing branch is not working at the moment. 
I guess I need you to grant me permission (in GitHub repo settings) to push branch into your repo and set up PR.
At the moment when I try to push:
`
C:\...>git push --set-upstream origin GetByIdStatusCodeFix
remote: Permission to fchristl/express-json-file-crud.git denied to hubert-wojtowicz.
fatal: unable to access 'https://github.com/fchristl/express-json-file-crud.git/': The requested URL returned error: 403
`

**Comment by fchristl** [comment]
Hi @hubert-wojtowicz, you are trying to push directly into my repository. What you can do is

1. Fork this repository by clicking the "Fork"  on the top right of https://github.com/fchristl/express-json-file-crud,
2. perform the changes in a branch of your fork,
3. push them to your fork,
4. open a pull request from your fork's branch against my master branch.

**Comment by fchristl** [comment]
Hi @hubert-wojtowicz , I just pushed and published version 0.0.4, which contains a fix for the wrong status code, along with a more testable architecture and actual test cases (yay).

**Comment by hubert-wojtowicz** [comment]
@fchristl, thanks. I'd it already fixed on my local branch, but I didn't have time to try your proposition with a fork. I see you made fare more inprovements than I suggested! Good luck!
