### ISSUE TITLE
Directory not automatically created

### ISSUE THREAD

**Issue by FrozenReality** [fchristl/express-json-file-crud#4]
According to the documentation both the directory and the file will be automatically created when they don't exist. This is only the case for the file, if the directory doesn't exist it throws an error:

`Error: ENOENT: no such file or directory, open './accounts/accounts.json'`

I did also notice that the "accounts" directory I was trying to make was in fact present the node_modules/express-json-file-crud directory.

(Love the project btw!)

**Comment by fchristl** [comment]
Oh, thank you! I believe the issue was introduced in https://github.com/fchristl/express-json-file-crud/pull/3 by using `__dirname`, which will be relative to `node_modules/express-json-file-crud`. I'll take a look at it as soon as I can.

**Comment by fchristl** [comment]
I fixed the issue and simplified the folder creation a bit. Version 0.0.7 is published with the fixes.
